# Jekyll configuration for HustleMode.AI

# Enable pretty URLs (removes .html extension from URLs)
permalink: /:title/

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock 